# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='parameterJSON',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
