# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0002_auto_20170923_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='trained',
            field=models.BooleanField(default=False),
        ),
    ]
