# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0004_prediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction',
            old_name='prediction',
            new_name='model',
        ),
    ]
