# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0005_auto_20170924_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='file',
            field=models.TextField(null=True),
        ),
    ]
