# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0006_predictionmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='predicting_complete',
            field=models.BooleanField(default=False),
        ),
    ]
