# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0007_predictionmodel_predicting_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionmodel',
            name='predicting_complete',
        ),
        migrations.AddField(
            model_name='prediction',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
